#!/usr/bin/awk -f
function s(t,i){while(match($0,t)){if(I[ni]==i)ni-=sub(t,"</"i">")
else if(sub(t,"<"i">"))I[++ni]=i}}BEGIN{FS="\n"; RS="";ni=0}
{$0=(match($0,/^(<.*>$|#)/))?$0:"<p>"$0"</p>"
gsub(/--/, "\\&mdash;", $0)
getline baseurl<"baseurl";
gsub(/img src="S\//, "img src=\"" baseurl "/S/", $0)
s("__","strong");s("\\*","em");s("`","code");
s("####", "h4");
s("###", "h3");
s("##", "h2");
s("#", "h1");
print}
